### ISSUE TITLE
New post / draft post template support?

### ISSUE THREAD

**Issue by phillipadsmith** [AlanBarber/jbh#1]
Howdy,

This looks like a great project. I'm going to give it a whirl this weekend.

Wondering if you're thinking about support for defining a template to use for new post creation vs. hard-coding the front matter in the script itself? 

There are also some good ideas here in relation to creating a folder for media assets too: http://harloholm.es/2014/04/23/neat-little-jekyll-trick.html

Cheers,

Phillip.

**Comment by AlanBarber** [comment]
That might be something I think could work. Were you thinking creating a "_template" folder that would contain a set of templates then specify a default template and command options for selecting templates?

**Comment by phillipadsmith** [comment]
> Were you thinking creating a "_template" folder that would contain a set of templates then specify a default template and command options for selecting templates?

Roughly, yes. 

Something like:

```jbh.sh --new "Blog title" --from "blog.md"```

Or 

```jbh.sh --new "Page title" --template "page"```

But, basically, yes: a way to pass the basic parameters/properties (title, date, etc.) to a template that contained other typical front matter for that type of document. 

I typically have A LOT of front matter in even simple blog posts, so having a lot of that pre-populated is super helpful, e.g., [here's a draft that I often instance new posts from](https://github.com/phillipadsmith/2014.phillipadsmith.com/blob/master/_drafts/2013-12-29-test-post-with-new-post-receive-hook.md)

**Comment by AlanBarber** [comment]
Thanks for the info. I like the --template style and think it works well

```jbh.sh --new "Page title" --template "page"```

I've added this as a milestone for the 1.3.0 release. I'm a tad bit swamped in the real world so I'm not sure when the release will get done, I'm setting Sept 15th just a rough estimate. Hopefully you can hold off until then.

**Comment by phillipadsmith** [comment]
> I've added this as a milestone for the 1.3.0 release. I'm a tad bit swamped in the real world so I'm not sure when the release will get done, I'm setting Sept 15th just a rough estimate. Hopefully you can hold off until then.

:+1: 

Totally. Nothing pressing on my end. Let me know if I can help in any way. :)

**Comment by AlanBarber** [comment]
For these templates what would you expect for how the title and date is added to the template?

I'm thinking it would require the templates to have custom tags added and then the script would insert the  values into those tags.

Example

````
---
layout: post
title: %title%
date: %date%
---
````

**Comment by phillipadsmith** [comment]
> For these templates what would you expect for how the title and date is added to the template?

> I'm thinking it would require the templates to have custom tags added and then the script would insert the values into those tags.

Makes total sense to me.

And, it could be very flexible if you could pass a hash/dictionary of arbitrary options to the template, e.g.:

`jbh.sh --new --template "page" --data title="My title" date="01/01/2015"`

I'm vague on how  parameter passing happens in a shell script, so there's probably a better format than the example above.

If that was possible, then the template could interpolate any number of arbitrary variables passed to the shell script  (assuming, of course, that the variables were indicated in the template).

Hope that helps a bit.

Phillip.
