### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by zenglian** [AlanBarber/jbh#6]
Per my test, step 3 in https://github.com/AlanBarber/jbh/wiki/Installing-RSync-on-Windows
should be modified to:
copy **all files** (maybe not all required, but 4 files is not enough) in C:\MinGW\msys\1.0\bin to C:\Program Files\Git\mingw64\bin
I'm on windows10, 64bit.

**Comment by daiyueweng** [comment]
yes, I can verify that `msys-1.0.dll` is also required to be copied over to `C:\Program Files\Git\mingw64\bin`, in order to make `rsync` work on `Win 10 X64`.

**Comment by AlanBarber** [comment]
updated wiki to include the new required msys file... 

on a side note I have since switched to the [Bash on Ubuntu on Windows](https://msdn.microsoft.com/en-us/commandline/wsl/install-win10) as it's much easier to run jekyll in a proper true linux environment.
